### ISSUE TITLE
Provide constants for RDF 1.1. Recommended XML Schema Data Types

### ISSUE THREAD

**Issue by dwvisser** [commons-rdf/commons-rdf#17]
I'm open as to how these are included, but I think it would be good to have them included, even if only as String constants somewhere with the full datatype IRIs as their values:

http://www.w3.org/TR/rdf11-concepts/#xsd-datatypes

**Comment by stain** [comment]
Given #47 and #30 and #48 and the 'dummy' implementation of #42 it should be easy to keep them as constants/enums - it should recommend to do `CONSTANT.equals(iri)` rather than `iri.equals(CONSTANT)` as the `IRI.equals()` of other implementations are permitted to check for local scope. (IRIImpl is happy as long as the strings match)

..or as an enum, you could have a `.asIRI(RDFTermFactory)` method - but that would look a bit more silly in comparisons (but allows any order of comparison):

```java
    RDFTermFactory rdffTermFactory = implementationSpecific();    
    if (literal.getDataType().equals(Types.XSD_DATETIME.asIRI(rdfTermFactory)) 
```

as opposed to:

```java
    if (Types.XSD_DATETIME.equals(literal.getDataType()))
```

**Comment by ansell** [comment]
I am not sure that we need the additional allowance that IRI.equals(IRI) can check for local scope. Graph.add(IRI, etc.,) could check for local scope and create a new object inside of that graph if the IRI originated outside of that scope, but that new object should still be .equals with the original IRI.

The only reason I was bringing up local scope yesterday was for the troublesome blank nodes.

**Comment by stain** [comment]
This Types looks good, but it does not implement/proxy IRI#equals and
hashcode - we can't expect every implementation to first check against
those constants as done in SimpleRDFTermFactory.

So what would happen with Types. XSD_BOOLEAN.equals(new IRIImpl("
http://www.w3.org/2001/XMLSchema#boolean")) ?

Also the toString of the enum would be XSD_UNSIGNEDINT etc which could be a
bit confusing.

**Comment by ansell** [comment]
Thanks, I will add equals and hashCode, not sure about toString, we haven't standardised that so far unless I am forgetting something. If we need to, we can add a method to it to return the IRI instance to avoid these issues.

**Comment by stain** [comment]
I was just thinking the toString difference would be confusing within
simple, as the factory now returns conditionally an IRIImpl or a Types
enum. (Which is good to me as the xsd Types will be duplicated a lot).

I don't think we should require anything about toString generally, as they
could already have a implementation-specific meaning. (e.g. "bnode 6363 in
graph 7373"). But within simple we can at least be consistent :-)
