### ISSUE TITLE
Transaction Model

### ISSUE THREAD

**Issue by wastl** [commons-rdf/commons-rdf#20]
In triple stores that have some sort of persistence, a transaction model is an important concept. I'd like to open the discussion how this can be integrated in a nice way with the pure OO commons-rdf. No real suggestion on this yet, though.

**Comment by ansell** [comment]
@wastl, now is probably a good time to experiment with this.

**Comment by stain** [comment]
Issue moved to https://issues.apache.org/jira/browse/COMMONSRDF-4
