### ISSUE TITLE
Stub implementations?

### ISSUE THREAD

**Issue by wikier** [commons-rdf/commons-rdf#22]
As discussed at issue #17, api will not be usable for the basics until the interfaces are not implemented. So the question for me is: are we going to provide stub implementations in this early stage or do we prefer to wait to have real implementations starting to adopt the interfaces?

Personally I'd prefer to wait, but I'd like to listen the opinion of @afs and @ansell from the implementors point of view.

**Comment by stain** [comment]
See stub implementations that are part of #42. They can be moved to `src/main/java` - perhaps be called something else than `dummyimpl` as they are not that dumb anymore.
