### ISSUE TITLE
Add RDFTermFactory

### ISSUE THREAD

**Issue by ansell** [commons-rdf/commons-rdf#26]
Should we add an RDFTermFactory interface with methods to map Java Types to RDF (particularly XML Schema) Literals, and allow creation of IRIs and BlankNodes?

**Comment by stain** [comment]
I would keep the complex datatype conversion as a part of the dummyimpl perhaps, and not require all implementations to support all of those. Given the local scope conversion it should work to pass such a `LiteralImpl` to other implementations (assuming they accept the datatype IRI)
