### ISSUE TITLE
Make Graph extend java.lang.AutoCloseable

### ISSUE THREAD

**Issue by ansell** [commons-rdf/commons-rdf#29]
If any Graph implementations have resources backing them, it may make operations more efficient if Graph extends AutoCloseable so that they can be used in try-with-resources blocks.

**Comment by stain** [comment]
As most graphs won't need to be close, there could be a default `close()` method in the Graph interface:

    default void close() throws Exception {}

**Comment by wikier** [comment]
+1 for using new [java8 `default`](http://docs.oracle.com/javase/tutorial/java/IandI/defaultmethods.html), but not sure all the issues discussed here can be solved in the same style...
