### ISSUE TITLE
Can Graph add duplicate triples?

### ISSUE THREAD

**Issue by stain** [commons-rdf/commons-rdf#44]
While implementing `GraphImpl` of #42, I was not sure what to do about multiple `add` of the same triple (either as same split-out argument or the actually same Triple instance). 

I assumed in the tests that this behaviour is "undefined" - perhaps this should be made explicit in the documentation of add()? 

Or should something happen, e.g. as in [java.util.Collection.add()](http://docs.oracle.com/javase/1.5.0/docs/api/java/util/Collection.html#add%28E%29) which has a `boolean` return value. (Incidentally the current `void` return value of `add` meant I could not easily subclass ArrayList to implement Graph - or in other words a `Graph` can't also be a `Collection`). Separate issue #46.

On the other hand I assume and made sure that `remove` removes all triples that match. One can imagine even in a non-duplicate environment for this to happen, e.g. a Graph that is a virtualization over multiple named graphs.

**Comment by ansell** [comment]
Some of the discussion in #27 may be relevant for background here.

In terms of matching triples using equals and hashCode, all of the RDFTerm's being added to a graph must either be from the expected implementation/local scope, or you must map them in the add method.

Ie, if GraphImpl.add is sent an RDFTerm that is implemented somewhere else, then you should check its class and any other hints about the locality of its scope within the add method, and create a new RDFTerm based on it if it came from outside of the local scope.

**Comment by ansell** [comment]
The rationale for that is to deal with blank node clashes, mostly, but also to deal with any caching or transaction state tracking that you are doing internally, which should be kept separate from any caching that other implementations may have been doing. Both of those may not be relevant to a simple dummy implementation, but they are relevant when we move to the intended scope of passing these objects between completely different implementations.

**Comment by stain** [comment]
`size` should anyway say something about the triple count possibly including duplicates or being overall inaccurate. 

(e.g. are you allowed to implement a quick-and-dirty size() that tells you to the nearest thousands for large datasets? Or are you required to basically do getTriples().count()? )

**Comment by afs** [comment]
A graph is a set of triples.  The count of a set does not include duplicates. Iteratation does not produce duplicates.

(An implementation may have duplicates purely internally though I find it hard to think why it would unless it is the computed composition of othe geaphs)
