### ISSUE TITLE
Can Graph be compatible with java.util.Collection?

### ISSUE THREAD

**Issue by stain** [commons-rdf/commons-rdf#46]
It would be nice if a `Graph` could also implement `java.util.Collection`. (I must admit this came up for me because I tried to just subclass `ArrayList` for my `GraphImpl` of #42.)

```
package com.github.commonsrdf.dummyimpl;

import java.util.Collection;
import java.util.Iterator;
import java.util.stream.Stream;

import com.github.commonsrdf.api.BlankNodeOrIRI;
import com.github.commonsrdf.api.Graph;
import com.github.commonsrdf.api.IRI;
import com.github.commonsrdf.api.RDFTerm;
import com.github.commonsrdf.api.Triple;

public class TestGraph implements Graph, Collection<Triple> {
	@Override
	public void add(BlankNodeOrIRI subject, IRI predicate, RDFTerm object) {	
	}
	@Override
	public boolean add(Triple e) {
		return false;
	}
	@Override
	public boolean addAll(Collection<? extends Triple> c) {
		return false;
	}
	@Override
	public void clear() {
	}
	@Override
	public boolean contains(BlankNodeOrIRI subject, IRI predicate,
			RDFTerm object) {
		return false;
	}
	@Override
	public boolean contains(Object o) {
		return false;
	}
	@Override
	public boolean contains(Triple triple) {
		return false;
	}
	@Override
	public boolean containsAll(Collection<?> c) {
		return false;
	}
	@Override
	public Stream<? extends Triple> getTriples() {
		return null;
	}
	@Override
	public Stream<? extends Triple> getTriples(BlankNodeOrIRI subject,
			IRI predicate, RDFTerm object) {
		return null;
	}	
	@Override
	public boolean isEmpty() {
		return false;
	}
	@Override
	public Iterator<Triple> iterator() {
		return null;
	}
	@Override
	public void remove(BlankNodeOrIRI subject, IRI predicate, RDFTerm object) {
	}
	@Override
	public boolean remove(Object o) {
		return false;
	}
	@Override
	public void remove(Triple triple) {
	}
	@Override
	public boolean removeAll(Collection<?> c) {
		return false;
	}
	@Override
	public boolean retainAll(Collection<?> c) {
		return false;
	}
	@Override
	public int size() {
		return 0;
	}
	@Override
	public Object[] toArray() {
		return null;
	}
	@Override
	public <T> T[] toArray(T[] a) {
		return null;
	}
}
```

gives two compliation errors:

```
[ERROR] /home/stain/src/commons-rdf/src/test/java/com/github/commonsrdf/dummyimpl/TestGraph.java:[13,16] com.github.commonsrdf.dummyimpl.TestGraph is not abstract and does not override abstract method size() in com.github.commonsrdf.api.Graph
[ERROR] /home/stain/src/commons-rdf/src/test/java/com/github/commonsrdf/dummyimpl/TestGraph.java:[81,28] size() in com.github.commonsrdf.dummyimpl.TestGraph cannot implement size() in com.github.commonsrdf.api.Graph
[ERROR] return type int is not compatible with java.lang.Long
```

The best way around this would be to rename `Graph.size()` to something like `tripleCount()` which is probably more accurate. 

But
```
[ERROR] /home/stain/src/commons-rdf/src/test/java/com/github/commonsrdf/dummyimpl/TestGraph.java:[18,32] add(com.github.commonsrdf.api.Triple) in com.github.commonsrdf.dummyimpl.TestGraph cannot implement add(com.github.commonsrdf.api.Triple) in com.github.commonsrdf.api.Graph
[ERROR] return type boolean is not compatible with void
```

is caused by `add` having a `void` return type. This should in-your-head compile, but in practice Java implements this by declaring it as a `java.lang.Void` return type - which is not compatible (or with anything (and can't be instantiated).

Would it make sense to adapt Java's boolean return type on `add`? It overlaps with #44 - but could be seen as a unnecessary burden to require a check for duplicate on insertion.

**Comment by ansell** [comment]
See issue #27 for some background on this.

**Comment by stain** [comment]
So the argument against `add` returning a `boolean` being difficult to predict in an industrial triple store, this can be augmented by documenting our `Graph.add` (and I guess `Graph.remove` to say that "Implementations MAY always return `false`, for instance for performance reasons." Similarly `size` should anyway say something about the triple count possibly including duplicates.

**Comment by afs** [comment]
The appraoch I prefer is to design for what an RDF API needs, then see if java.util.Collection is suitable.  I'd also like to see a use case, not some abstract sense of "good design", where viewing a graph as a collection is useful (and surely its `Set<Triple>`). If an exact fit is not possible, then maybe a view method e.g. `Set<Triple> asSet()`.

Dataset-as-collection is harder.  It is a not a set of some fixed item type.

**Comment by stain** [comment]
I think most of the "good things" from Set, e.g. unions and differences we
would get automatically from Stream of `getTriples` - so perhaps there is
no good use case for this. Close this issue?

On 14 January 2015 at 10:55, Andy Seaborne <notifications@github.com> wrote:

> The appraoch I prefer is to design for what an RDF API needs, then see if
> java.util.Collection is suitable. I'd also like to see a use case, not some
> abstract sense of "good design", where viewing a graph as a collection is
> useful (and surely its Set<Triple>). If an exact fit is not possible,
> then maybe a view method e.g. Set<Triple> asSet().
>
> Dataset-as-collection is harder. It is a not a set of some fixed item type.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commons-rdf/commons-rdf/issues/46#issuecomment-69899825>
> .
>



-- 
Stian Soiland-Reyes, myGrid team
School of Computer Science
The University of Manchester
http://soiland-reyes.com/stian/work/ http://orcid.org/0000-0001-9842-9718

**Comment by afs** [comment]
Happy to close, esp as I think that the Set unions and differences design is not appropriate.  It is useful as convneince to small scale, in-memory Java sets that mutate the target.

**Comment by stain** [comment]
OK, I give in and closed this :) Thanks for clarifying!
