### ISSUE TITLE
Add immutability to the API for all RDFTerm and Triple instances

### ISSUE THREAD

**Issue by ansell** [commons-rdf/commons-rdf#57]
As mentioned in #45, should we add a contract requirement that all RDFTerm instances (and Triple?) be implemented as immutable objects?

**Comment by stain** [comment]
+1, if we say SHOULD. But only the exposed RDFTerm++ methods need to be immutable - so this should probably go into each of their descriptions. So if I have a `getDatabaseThingie()` method that can be mutable.

**Comment by ansell** [comment]
The value of stating that the objects must be immutable is decreased if it only applies to the results of the API methods. A useful goal would be to ensure that the entire object is immutable to give a guarantee about threadsafety, but that may be too much for all implementations to support.

Just stating that the results of the visible API methods are immutable doesn't help much. It is also not likely to apply to the methods that return Optional, as to enable serialisation, the actual field may not be an Optional itself in most cases.

**Comment by stain** [comment]
Moved to https://issues.apache.org/jira/browse/COMMONSRDF-7
